apiVersion: v1
kind: Secret
metadata:
  name: finance-secrets
  namespace: personal-finance
type: Opaque
stringData:
  django-secret-key: "change-me-in-production"
  postgres-password: "finance"
  mongo-password: "finance"
